---
# tasks file for 05-workers-add-on-workers
# hosts: worker

- name: join cluster
  shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt